#!/bin/sh

echo Combining and minifying JavaScript...
cat js/bootstrap-transition.js js/bootstrap-alert.js js/bootstrap-button.js js/bootstrap-carousel.js js/bootstrap-collapse.js js/bootstrap-dropdown.js js/bootstrap-modal.js js/bootstrap-tooltip.js js/bootstrap-popover.js js/bootstrap-scrollspy.js js/bootstrap-tab.js js/bootstrap-typeahead.js js/bootstrap-affix.js > js/bootstrap.js
cat js/jquery-1.8.*.js js/jquery.tablesorter.js js/bootstrap.js js/evething.js > static/js/evething.js
uglifyjs -nc static/js/evething.js > static/js/evething.min.js

echo Building theme-default...
recess --compress less/theme-default/bootstrap.less > static/css/theme-default.min.css

echo Building theme-slate...
recess --compress less/theme-slate/bootstrap.less > static/css/theme-slate.min.css

echo Building theme-cyborg...
recess --compress less/theme-cyborg/bootstrap.less > static/css/theme-cyborg.min.css

echo Building theme-cerulean...
recess --compress less/theme-cerulean/bootstrap.less > static/css/theme-cerulean.min.css

#spritemapper base_static/css/icons-default.css
#spritemapper base_static/css/icons-fugue-stars.css
