#!/bin/sh
echo Building theme-default...
recess --compress less/theme-default/bootstrap.less > base_static/css/theme-default.min.css

echo Building theme-slate...
recess --compress less/theme-slate/bootstrap.less > base_static/css/theme-slate.min.css

echo Building theme-cyborg...
recess --compress less/theme-cyborg/bootstrap.less > base_static/css/theme-cyborg.min.css

echo Building theme-cerulean...
recess --compress less/theme-cerulean/bootstrap.less > base_static/css/theme-cerulean.min.css

#spritemapper base_static/css/icons-default.css
#spritemapper base_static/css/icons-fugue-stars.css
