#!/bin/sh

# cat static/js/bootstrap-transition.js static/js/bootstrap-alert.js static/js/bootstrap-button.js static/js/bootstrap-carousel.js static/js/bootstrap-collapse.js static/js/bootstrap-dropdown.js static/js/bootstrap-modal.js static/js/bootstrap-tooltip.js static/js/bootstrap-popover.js static/js/bootstrap-scrollspy.js static/js/bootstrap-tab.js static/js/bootstrap-typeahead.js static/js/bootstrap-affix.js > static/js/bootstrap.js
BOOTSTRAP_SRC="static/js/bootstrap-alert.js static/js/bootstrap-button.js static/js/bootstrap-collapse.js static/js/bootstrap-dropdown.js static/js/bootstrap-modal.js static/js/bootstrap-tooltip.js static/js/bootstrap-popover.js static/js/bootstrap-tab.js static/js/bootstrap-scrollspy.js static/js/bootstrap-affix.js"

echo Combining and minifying JavaScript...
cat $BOOTSTRAP_SRC > static/js/bootstrap.js
#cat static/js/bootstrap-alert.js static/js/bootstrap-button.js static/js/bootstrap-collapse.js static/js/bootstrap-dropdown.js static/js/bootstrap-modal.js static/js/bootstrap-tooltip.js static/js/bootstrap-popover.js static/js/bootstrap-tab.js static/js/bootstrap-scrollspy.js static/js/bootstrap-affix.js > static/js/bootstrap.js
cat static/js/jquery-2.*.js static/js/jquery.tablesorter.js static/js/bootstrap.js static/js/bootstrap-datepicker.js static/js/evething.js > static/js/evething-combined.js
uglifyjs static/js/evething-combined.js -c > static/js/evething-combined.min.js

echo Building theme-default...
recess --compress static/less/theme-default/bootstrap.less > static/css/theme-default.min.css

echo Building theme-darkthing...
recess --compress static/less/theme-darkthing/bootstrap.less > static/css/theme-darkthing.min.css

echo Building theme-slate...
recess --compress static/less/theme-slate/bootstrap.less > static/css/theme-slate.min.css

echo Building theme-cyborg...
recess --compress static/less/theme-cyborg/bootstrap.less > static/css/theme-cyborg.min.css

echo Building theme-cerulean...
recess --compress static/less/theme-cerulean/bootstrap.less > static/css/theme-cerulean.min.css
