# Pull base image.
FROM ubuntu:14.04

MAINTAINER Eric Gillingham "Eric.J.Gillingham@jpl.nasa.gov"

# Install.
RUN sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
apt-get update && \
apt-get -y upgrade && \
apt-get install -y python2.7 python2.7-dev python-virtualenv python-pip \
                    libpq-dev \
                    nodejs nodejs-legacy npm \
                    build-essential wget && \
/usr/bin/virtualenv /evething-env

ADD . /evething
WORKDIR /evething

# Check for data dump
RUN if [ ! -e sqlite-latest.sqlite ]; then wget https://www.fuzzwork.co.uk/dump/sqlite-latest.sqlite.bz2 && bunzip2 sqlite-latest.sqlite.bz2 ; fi

# Install python deps into virtualenv, and activate at login
RUN . /evething-env/bin/activate && \
pip install -r /evething/requirements.txt -r /evething/docker/requirements-docker.txt -r /evething/docker/requirements-docker-dev.txt && \
echo '. /evething-env/bin/activate' >> /root/.bashrc

# Install npm deps and add to PATH
RUN npm install && \
npm install npm-check-updates && \
echo 'export PATH=${PATH}:/evething/node_modules/.bin' >> /root/.bashrc

# Define default command, this gets overwritten by docker-compose
CMD ["bash"]
