# Pull base image.
FROM nginx

MAINTAINER Eric Gillingham "Eric.J.Gillingham@jpl.nasa.gov"

# Copy custom configuration file from the current directory
COPY docker/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx"]